[package]
name = "owl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
crossbeam-channel = "0.5.15"
reqwest = { version = "0.12.24", features = ["blocking"] }
zip = "6.0.0"
