[package]
name = "owl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
dirs = "6.0.0"
reqwest = { version = "0.12.24", features = ["blocking"] }
toml_edit = "0.23.7"
zip = "6.0.0"
